services:
  - type: web
    name: kravanh-pos
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://promotion-management-eybk.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_DOMAIN
        value: promotion-management-eybk.onrender.com
      - key: SESSION_SAME_SITE
        value: none
      - key: SESSION_HTTP_ONLY
        value: true
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
